name: deployment 
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deployment script
      uses: appleboy/ssh-action@master
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        TEMPERATURES_DB_PASSWORD: ${{ secrets.TEMPERATURES_DB_PASSWORD }}
        RASP_ADDRESS: ${{ secrets.RASP_ADDRESS }}
        RASP_PORT: ${{ secrets.RASP_PORT }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        envs: SECRET_KEY,TEMPERATURES_DB_PASSWORD,RASP_ADDRESS,RASP_PORT
        script: |
          pkill -15 webapp.py
          cd /home/ec2-user/webapp
          git pull origin master
          /home/ec2-user/webapp/webapp.py &> /home/ec2-user/webapp/Logs/webapp_logs.txt &
